[#5] 검색 구현
2024Hanium-Allclear/Allclear pull request #8
Opened 2024-07-21 09:00 UTC by MinCodeHub

## Self-Check Guidelines
- 코드
  - [ ] 커밋 메시지, 코딩 컨벤션 준수
  - [ ] 테스트 동작 확인
  - [ ] base 브랜치의 최신 내용 반영
- PR
  - [ ] base 브랜치, head 브랜치 확인
  - [ ] 우측 assignee(담당자), reviewers(코드 리뷰할 팀원), 관련 label 태깅
  - [ ] 제목: [#이슈번호] PR 요약
  - [ ] 본문: 각 설명에 따라 내용 작성

## Summary

## Description
개설학과 옵션으로 검색
교과목명 옵션으로 검색
학수번호 옵션으로 검색

## Issue
#5 

아직 남은 일

- [ ] JPQL을 사용했는데 JPA ORM을 최대한 이용해서 JPQL 사용을 줄일 예정
- [ ] CSS 입히기
- [ ] 세세한 예외 처리
- [ ] 테스트코드 작성

2024-07-21 10:51 UTC, yeon2lee requested changes

2024-07-21 10:51 UTC, yeon2lee commented on allclear-course/src/main/java/com/project/allclear_course/controller/api/LectureApiController.java
> +        Lecture lecture = new Lecture();
setter도 괜찮긴 한데 dto에서 entity 변환할 때 LectureDto에 toEntity() 메소드 만들어서 해봐도 좋을 것 같아~~ `@Builder`도 써보면 좋구
시간 되면 해보는 거 추천!

2024-07-21 10:51 UTC, yeon2lee commented on allclear-course/src/main/java/com/project/allclear_course/controller/api/LectureApiController.java
> +                    .orElseThrow(() -> new IllegalArgumentException("Invalid department ID"));
예외 처리한 거 굿굿👍👍

2024-07-21 10:51 UTC, yeon2lee commented on allclear-course/src/main/java/com/project/allclear_course/controller/api/SearchLectureApiController.java
> +@RequestMapping("/lectures/api")
`@RequestMapping("api/lectures")` 로 순서 바꾸는 게 좋을 것 같아!

2024-07-21 10:51 UTC, yeon2lee commented on allclear-course/src/main/java/com/project/allclear_course/domain/entity/Lecture.java
> +@Setter
Entity에 setter를 선언하면 어디서든 entity에 접근이 가능해져서 의도치 않게 데이터가 변경될 수도 있고 객체 일관성이 깨질 수 있어서 Entity에서는 setter 사용을 지양하는 게 좋다고 하더라구.. 그래서 최대한 setter 안 쓰는 게 좋을 것 같엉

2024-07-21 10:51 UTC, yeon2lee commented on allclear-course/src/main/java/com/project/allclear_course/init/DataInitializer.java
> +public class DataInitializer {
👍👍 진짜 고생많았다..

2024-07-22 09:21 UTC, MinCodeHub commented on allclear-course/src/main/java/com/project/allclear_course/controller/api/LectureApiController.java
> +        Lecture lecture = new Lecture();
오호 오키오키! 해볼게요~!

2024-08-14 05:33 UTC, yeon2lee approved these changes

2024-08-14 05:33 UTC, merged